pipeline:
  build:
    image: plugins/docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    repo: registry.elbert.us/dungeon
    registry: registry.elbert.us
    tags:
      - latest
      - "${DRONE_BRANCH}"
    secrets: [ docker_username, docker_password ]

  deploy:
    image: registry.elbert.us/drone_rlyeh_deploy
    pull: true
    secrets: [ rlyeh_deploy_key ]
    user: fig
    deploy_name: dungeon
    compose_file: 'docker-compose-rlyeh.yml'
    when:
      branch: production
