mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=mysupersecret
  volumes_from:
    - dungeon_db_data


redis:
  image: redis:latest


web:
  build: .
  environment:
    - RAILS_ENV=docker
  links:
    - redis
    - mysql