mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=mysupersecret
  volumes_from:
    - dungeon_db_data


redis:
  image: redis:latest


web1:
  build: .
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=docker
  links:
    - redis
    - mysql