version: '2'

services:
  redis:
    image: redis:latest

  proxy:
    image: 'nginx:latest'
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - assets:/dungeon/public/assets/
      - images:/dungeon/public/images/
    links:
      - web1
      - web2
      - web3
      - web4

  web1:
    image: 'danelbert/dungeon:production'
    env_file: /etc/default/dungeon
    environment:
      - COPY_ASSETS=true
    volumes:
      - assets:/dungeon_assets/
      - images:/dungeon/public/images/
    links:
      - redis

  web2: &web
    image: 'danelbert/dungeon:production'
    env_file: /etc/default/dungeon
    volumes:
      - images:/dungeon/public/images/
    links:
      - redis

  web3:
    <<: *web

  web4:
    <<: *web

volumes:
  assets:
    driver: local

