
redis:
  image: 'redis:latest'

proxy:
  image: 'danelbert/nginx:latest'
  ports:
    - "3000:80"
  volumes_from:
    - web1
  volumes:
    - docker/nginx_proxy.conf:/etc/nginx/conf.d/default.conf
  links:
    - web1
    - web2
    - web3
    - web4


web1:
  image: 'danelbert/dungeon:production'
  environment:
    - RAILS_ENV=production
    - SHARE_ASSETS=true
  env_file: /etc/default/dungeon
  volumes:
    - /dungeon/public
    - log:dungeon/log
  links:
    - redis


web2: &web
  image: 'danelbert/dungeon:production'
  environment:
    - RAILS_ENV=production
  env_file: /etc/default/dungeon
  volumes_from:
    - web1
  links:
    - redis


web3:
  <<: *web

web4:
  <<: *web