version: '3'

services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=dungeon
    volumes:
      - sql-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  proxy:
    image: 'nginx:latest'
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - assets:/dungeon/public/assets/
      - images:/dungeon/public/images/
    depends_on:
      - web1
      - web2
      - web3
      - web4

  web1:
    build: .
    image: 'danelbert/dungeon:beta'
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=1c0fb1f70630f29ccc573c6c8438bba76f93423f4dc2aa3f1d2de7a53734e6ae8e88defb36c2f802c023b994355ad1c4b9775154d65fcfdd7ab41d82f211763d
      - COPY_ASSETS=true
      - LOGLEVEL=debug
    volumes:
      - assets:/dungeon_assets/
      - images:/dungeon/public/images/
      - logs:/dungeon/log
    depends_on:
      - redis
      - postgres

  web2: &web
    image: 'danelbert/dungeon:beta'
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=1c0fb1f70630f29ccc573c6c8438bba76f93423f4dc2aa3f1d2de7a53734e6ae8e88defb36c2f802c023b994355ad1c4b9775154d65fcfdd7ab41d82f211763d
      - LOGLEVEL=debug
    volumes:
      - images:/dungeon/public/images/
      - logs:/dungeon/log
    depends_on:
      - redis
      - postgres

  web3:
    <<: *web

  web4:
    <<: *web

volumes:
  sql-data:
    driver: local

  assets:
    driver: local

  images:
    driver: local

  logs:
    driver: local


