version: '2'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./dungeon_nginx:/etc/nginx/conf.d/
      - assets:/dungeon/public/assets/
      - images:/dungeon/public/images/
    links:
      - web1
      - web2
      - web3
      - web4

  web1:
    image: 'danelbert/dungeon:production'
    restart: unless-stopped
    env_file: /etc/default/dungeon
    environment:
      - COPY_ASSETS=true
      - DB_MIGRATE=true
    volumes:
      - assets:/dungeon_assets/
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    links:
      - redis

  web2: &web
    image: 'danelbert/dungeon:production'
    restart: unless-stopped
    env_file: /etc/default/dungeon
    volumes:
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    links:
      - redis

  web3:
    <<: *web

  web4:
    <<: *web

volumes:
  assets:
    driver: local

  images:
    driver: local



