version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    volumes:
      - ./dungeon_nginx:/etc/nginx/conf.d/
      - assets:/dungeon/public/assets/
      - images:/dungeon/public/images/
    links:
      - web1
      - web2
      - web3
      - web4
    networks:
      - default
      - traefik
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik
      traefik.frontend.rule: 'Host:dungeon.elbert.us'

  web1:
    image: 'registry.elbert.us/dungeon:production'
    restart: unless-stopped
    env_file: /etc/default/dungeon
    environment:
      - COPY_ASSETS=true
      - DB_MIGRATE=true
    volumes:
      - assets:/dungeon_assets/
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    links:
      - redis

  web2: &web
    image: 'registry.elbert.us/dungeon:production'
    restart: unless-stopped
    env_file: /etc/default/dungeon
    volumes:
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    links:
      - redis

  web3:
    <<: *web

  web4:
    <<: *web

  worker:
    image: 'registry.elbert.us/dungeon:production'
    restart: unless-stopped
    env_file: /etc/default/dungeon
    volumes:
    - images:/dungeon/public/images/
    - /var/log/dungeon:/dungeon/log/
    links:
    - redis

volumes:
  assets:
    driver: local

  images:
    driver: local

networks:
  traefik:
    external: true

