
redis:
  image: 'redis:latest'

mysql:
  image: 'mysql:5.6'
  environment:
    - MYSQL_ROOT_PASSWORD=mysupersecret
    - MYSQL_DATABASE=dungeon
    - MYSQL_USER=dungeon_user
    - MYSQL_PASSWORD=dungeon_password
  volumes_from:
    - dungeon_db_data

proxy:
  image: 'danelbert/nginx:latest'
  ports:
    - "80:80"
  volumes_from:
    - web1
  volumes:
    - docker/nginx_proxy.conf:/etc/nginx/conf.d/default.conf
  links:
    - web1
    - web2
    - web3
    - web4


web1:
  image: 'danelbert/dungeon:beta'
  environment:
    - RAILS_ENV=production
    - SHARE_ASSETS=true
  volumes:
    - /dungeon/public
    - log:dungeon/log
  links:
    - redis
    - mysql


web2: &web
  image: 'danelbert/dungeon:beta'
  environment:
    - RAILS_ENV=production
  volumes_from:
    - web1
  links:
    - redis
    - mysql


web3:
  <<: *web

web4:
  <<: *web