version: '3'

services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=dungeon
    volumes:
      - sql-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  web1:
    build: .
    image: 'registry.elbert.us/dungeon'
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=docker
      - DB_MIGRATE=true
    volumes:
      - images:/dungeon/public/images/
    links:
      - redis
      - postgres

  resque_worker:
    build: .
    image: 'registry.elbert.us/dungeon'
    environment:
      - RAILS_ENV=docker
      - QUEUE=*
      - INTERVAL=1.0
    volumes:
      - images:/dungeon/public/images/
    command: 'bundle exec rake resque:work'
    links:
      - redis
      - postgres

volumes:
  sql-data:
    driver: local

  images:
    driver: local