version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  nginx:
    image: 'registry.elbert.us/dungeon:${IMAGE_TAG}'
    restart: unless-stopped
    volumes:
      - images:/dungeon/public/images/
    networks:
      - traefik
    command: ["nginx", "-g", "daemon off;"]
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik
      traefik.frontend.rule: 'Host:${HOSTNAME};Path:/assets,/packs,/favicon.ico,/robots.txt'

  web1: &web
    image: 'registry.elbert.us/dungeon:${IMAGE_TAG}'
    restart: unless-stopped
    environment:
      - DB_MIGRATE=true
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DUNGEON_PG_HOST=${DUNGEON_PG_HOST}
      - DUNGEON_PG_USER=${DUNGEON_PG_USER}
      - DUNGEON_PG_PASSWORD=${DUNGEON_PG_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD='${SMTP_PASSWORD}'

    volumes:
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    links:
      - redis
    networks:
      - traefik
      - default
    labels:
      traefik.enable: 'true'
      traefik.docker.network: traefik
      traefik.frontend.rule: 'Host:${HOSTNAME}'
      traefik.backend: 'dungeon'

  web2:
    <<: *web
    environment:
      - DB_MIGRATE=false
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DUNGEON_PG_HOST=${DUNGEON_PG_HOST}
      - DUNGEON_PG_USER=${DUNGEON_PG_USER}
      - DUNGEON_PG_PASSWORD=${DUNGEON_PG_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD='${SMTP_PASSWORD}'

  web3:
    <<: *web
    environment:
      - DB_MIGRATE=false
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DUNGEON_PG_HOST=${DUNGEON_PG_HOST}
      - DUNGEON_PG_USER=${DUNGEON_PG_USER}
      - DUNGEON_PG_PASSWORD=${DUNGEON_PG_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD='${SMTP_PASSWORD}'

  web4:
    <<: *web
    environment:
      - DB_MIGRATE=false
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DUNGEON_PG_HOST=${DUNGEON_PG_HOST}
      - DUNGEON_PG_USER=${DUNGEON_PG_USER}
      - DUNGEON_PG_PASSWORD=${DUNGEON_PG_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD='${SMTP_PASSWORD}'

  worker:
    image: 'registry.elbert.us/dungeon:${IMAGE_TAG}'
    restart: unless-stopped
    volumes:
      - images:/dungeon/public/images/
      - /var/log/dungeon:/dungeon/log/
    environment:
      - QUEUE=*
      - INTERVAL=1.0
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DUNGEON_PG_HOST=${DUNGEON_PG_HOST}
      - DUNGEON_PG_USER=${DUNGEON_PG_USER}
      - DUNGEON_PG_PASSWORD=${DUNGEON_PG_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD='${SMTP_PASSWORD}'
    command: 'bundle exec rake resque:work'
    links:
    - redis

volumes:
  images:
    driver: local

networks:
  traefik:
    external: true

